apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv
  labels:
    volume: ssd
spec:
  storageClassName: "manual"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: enter-IP-address
    # Exported path of your NFS server
    path: "/test"