apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv2
  labels:
    volume: hdd
spec:
  storageClassName: "manual"
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: enter-IP-address
    # Exported path of your NFS server
    path: "/test2"