apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc2
  labels:
    app: wordpress
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      volume: hdd