apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp
  name: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp
    spec:
      containers:
      - image: wordpress:latest
        name: wordpresss
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: redhat
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: myvol1
          mountPath: /var/www/html
      volumes:
      - name: myvol1
        persistentVolumeClaim:
          claimName: mypvc2